# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'jack', '0001_initial'), (b'jack', '0002_jackinfo_type'), (b'jack', '0003_auto_20161026_1213'), (b'jack', '0004_auto_20161027_1437'), (b'jack', '0005_auto_20161101_1233'), (b'jack', '0006_auto_20161101_1235'), (b'jack', '0007_auto_20161101_1339'), (b'jack', '0008_auto_20161101_1344'), (b'jack', '0009_auto_20161101_1400'), (b'jack', '0010_auto_20161101_1405'), (b'jack', '0011_auto_20161101_1406'), (b'jack', '0012_auto_20161101_1408'), (b'jack', '0013_auto_20161102_0848'), (b'jack', '0014_auto_20161102_1451')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='jack.BuildingName')),
                ('room_number', models.CharField(max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('port_number', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='jack.JackType')),
                ('phone_extension', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InPlateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.ForeignKey(blank=True, default='quad', on_delete=django.db.models.deletion.CASCADE, related_name='in_plate_type', to='jack.InPlateType'),
            preserve_default=False,
        ),
    ]
