# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingname', models.CharField(max_length=50)),
                ('roomnumber', models.CharField(max_length=10)),
                ('person', models.CharField(max_length=50)),
                ('callerid', models.CharField(max_length=50)),
                ('portnumber', models.CharField(max_length=50)),
                ('portstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
