# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0002_jackinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
