# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0004_auto_20161027_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackinfo',
            name='person',
        ),
        migrations.RemoveField(
            model_name='jackinfo',
            name='portstatus',
        ),
        migrations.AddField(
            model_name='jackinfo',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='callerid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
