# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0005_auto_20161101_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackinfo',
            old_name='phonenumber',
            new_name='phone_extension',
        ),
    ]
