# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0006_auto_20161101_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackinfo',
            old_name='buildingname',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='jackinfo',
            old_name='callerid',
            new_name='caller_id',
        ),
        migrations.RenameField(
            model_name='jackinfo',
            old_name='portnumber',
            new_name='port_number',
        ),
        migrations.RenameField(
            model_name='jackinfo',
            old_name='roomnumber',
            new_name='room_number',
        ),
    ]
