# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0007_auto_20161101_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='BuildingName',
        ),
    ]
