# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0009_auto_20161101_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='building_name',
            field=models.CharField(max_length=50),
        ),
    ]
