# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0010_auto_20161101_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='jack.BuildingName'),
        ),
    ]
