# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0013_auto_20161102_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPlateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='in_plate_type', to='jack.InPlateType'),
            preserve_default=False,
        ),
    ]
