# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0015_remove_jackinfo_in_plate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='in_plate_type', to='jack.InPlateType'),
        ),
    ]
