# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0016_jackinfo_in_plate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackinfo',
            name='in_plate_type',
        ),
    ]
