# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0020_auto_20161103_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_room', models.CharField(max_length=10)),
                ('first_number', models.CharField(max_length=10)),
                ('first_extension', models.CharField(max_length=10)),
                ('second_room', models.CharField(max_length=10)),
                ('second_number', models.CharField(max_length=10)),
                ('second_extension', models.CharField(max_length=10)),
                ('first_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jack.BuildingName')),
                ('second_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jack.BuildingName')),
            ],
        ),
    ]
