# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0021_swapmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='jackinfo',
            name='active',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='active', to='jack.Active'),
        ),
    ]
