# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0022_auto_20161116_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='jack.Active'),
        ),
    ]
