# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0023_auto_20161117_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active', to='jack.Active'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='building_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='jack.BuildingName'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_plate_type', to='jack.InPlateType'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='port_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='jack.JackType'),
        ),
    ]
