# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0024_auto_20161117_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inplatetype',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
