# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0025_auto_20161117_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapmodel',
            name='first_building',
        ),
        migrations.RemoveField(
            model_name='swapmodel',
            name='second_building',
        ),
        migrations.RemoveField(
            model_name='jackinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='jackinfo',
            name='jack_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='active',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='building_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Active',
        ),
        migrations.DeleteModel(
            name='BuildingName',
        ),
        migrations.DeleteModel(
            name='InPlateType',
        ),
        migrations.DeleteModel(
            name='JackType',
        ),
        migrations.DeleteModel(
            name='SwapModel',
        ),
    ]
