# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0026_auto_20161117_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InPlateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SwapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_room', models.CharField(max_length=10)),
                ('first_number', models.CharField(max_length=10)),
                ('first_extension', models.CharField(max_length=10)),
                ('second_room', models.CharField(max_length=10)),
                ('second_number', models.CharField(max_length=10)),
                ('second_extension', models.CharField(max_length=10)),
                ('first_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jack.BuildingName')),
                ('second_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jack.BuildingName')),
            ],
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active', to='jack.Active'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='building_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='jack.BuildingName'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='in_plate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_plate_type', to='jack.InPlateType'),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='jack_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jack_type', to='jack.JackType'),
        ),
    ]
