# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0027_auto_20161117_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingname',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='room_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
