# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0029_auto_20161121_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='port_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackinfo',
            name='room_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
