# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='checkout_flag',
            new_name='checkedin_flag',
        ),
    ]
