# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20170511_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='fac_user',
        ),
        migrations.AddField(
            model_name='rental',
            name='student_user',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
