# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_checkout_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_history',
            name='device',
        ),
        migrations.RemoveField(
            model_name='checkout_history',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='checkout_history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Checkout_History',
        ),
    ]
