# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20170511_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='fac_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='student_user',
        ),
    ]
