# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20170526_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='checkedin_flag',
        ),
    ]
