# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appliance',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='building_location',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='room_location',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='display',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misc_hardware',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='id',
        ),
        migrations.AddField(
            model_name='computer',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misc_hardware',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projector',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ComputerType'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Processor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='resolution',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Resolution'),
        ),
        migrations.AlterField(
            model_name='display',
            name='video_inputs',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Input'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='toner',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Toner'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='make',
            field=models.CharField(blank=True, default='String', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projector',
            name='model',
            field=models.CharField(blank=True, default='String', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projector',
            name='video_inputs',
            field=models.ForeignKey(blank=True, default='String', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Input'),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
