# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170303_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device')),
                ('applicance_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device')),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('inventory.device',),
        ),
    ]
