# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_appliance_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='hostname',
        ),
        migrations.AddField(
            model_name='computer',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.ManyToManyField(to='inventory.MacAddress'),
        ),
    ]
