# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170307_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='f_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
