# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_device_f_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
