# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170315_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ComputerType'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Processor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.MacAddress'),
        ),
        migrations.AlterField(
            model_name='warrantytype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
