# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170411_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Resolution'),
        ),
        migrations.AlterField(
            model_name='display',
            name='video_inputs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Input'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Toner'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projector',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projector',
            name='video_inputs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Input'),
        ),
    ]
