# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170424_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='applicance_name',
            new_name='appliance_name',
        ),
    ]
