# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170424_1409'),
        ('inventory', '0010_auto_20170426_0022'),
    ]

    operations = [
    ]
