# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_merge_20170502_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
