# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170502_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='appliance_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
